name: smartroute
description: "SmartRoute - Klang Valley Transit Companion"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.17
  supabase_flutter: ^2.17.2
  google_maps_flutter: ^2.18.0
  geolocator: ^14.0.3
  http: ^1.6.0
  gtfs_realtime_bindings: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  mocktail: ^1.0.5

flutter:
  uses-material-design: true

  assets:
    - assets/data/transit_network.json
